spring.application.name=5-jpa-relations-ogreniyorum

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.jpa.properties.hibernate.default_schema=customers
spring.datasource.username=postgres
spring.datasource.password=bxgyrf71

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
